# Generated by Django 4.2.5 on 2023-09-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='farmer', to='agro.product'),
        ),
    ]
