# Generated by Django 4.2.5 on 2023-09-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0003_alter_farmerprofile_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
