# Generated by Django 4.2.5 on 2023-10-01 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0004_contactsubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactSubmission',
        ),
    ]
