# Generated by Django 4.2.5 on 2023-10-01 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0005_delete_contactsubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_listed']},
        ),
    ]
