# Generated by Django 4.2.5 on 2023-10-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0007_alter_blogpost_options_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
